## Cross Validation


We can : 


1-> Use all the data for the training purpose 

2-> Split the data in training data and testing data in proporting of (70:30 or 80:20).


3-> Divide the data in k no. of folds. We do iterations, in each iteration we use all the folds (except one of them), perform traing and perform testing on the fold wich was not used in trainig. After all iterations we calculate average of all the testing and model which gives best score is likely to be selected. One fold fro testing and remaining k-1 folds for the training.

In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

import numpy as np
import pandas as pd
from sklearn.datasets import load_digits

In [2]:
digits = load_digits()

In [3]:
type(digits)

sklearn.utils._bunch.Bunch

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size= 0.2)

In [5]:
#Logistic Regression
lr = LogisticRegression(solver="liblinear", multi_class='ovr')
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

C:\Users\Aditya\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


0.9638888888888889

In [6]:
#SVM
svc = SVC(gamma='auto')
svc.fit(X_train, y_train)
svc.score(X_test, y_test)

0.4111111111111111

In [7]:
#Random Forest
rf = RandomForestClassifier(n_estimators=10)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9472222222222222

In [8]:
#K fold cross validation

from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

Take a look on how cross validation divides the data in the folds

In [9]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [10]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [15]:
scores_l = []
scores_svc = []
scores_rf = []


for train_index, test_index in kf.split(digits.data, digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    
    scores_l.append(get_score(LogisticRegression(solver="liblinear"), X_train, X_test, y_train, y_test))
    scores_svc.append(get_score(SVC(gamma = 'auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators = 40), X_train, X_test, y_train, y_test))

In [16]:
print(scores_l)
print(scores_svc)
print(scores_rf)

[0.8964941569282137, 0.9515859766277128, 0.9115191986644408]
[0.41068447412353926, 0.41569282136894825, 0.4273789649415693]
[0.9265442404006677, 0.9449081803005008, 0.9215358931552587]


The leathy code can be replace with the functionalities in the sklearn

In [17]:
#Cross_val_score function
from sklearn.model_selection import cross_val_score

In [21]:
cross_val_score(LogisticRegression(solver='liblinear'), digits.data, digits.target)

array([0.92222222, 0.88333333, 0.95264624, 0.95821727, 0.89415042])

In [22]:
cross_val_score(SVC(gamma='auto'), digits.data, digits.target)

array([0.41111111, 0.45      , 0.454039  , 0.44846797, 0.47910864])

In [23]:
cross_val_score(RandomForestClassifier(n_estimators=30), digits.data, digits.target)

array([0.91944444, 0.88888889, 0.94150418, 0.97214485, 0.91086351])